
CC= g++
std= -std=c++11


myAppStore: myAppStore.cpp prime.cc userFunctions.cpp defn.h projectHeader.h 

			$(CC) $(std) myAppStore.cpp prime.cc userFunctions.cpp defn.h projectHeader.h -o myAppStore
